### ISSUE TITLE
关于cnn网络结构疑惑

### ISSUE THREAD

**Issue by snowlord** [white127/insuranceQA-cnn-lstm#1]
![image](https://cloud.githubusercontent.com/assets/8564700/18781837/119403dc-81b6-11e6-9d2c-f229f52e5138.png)

网络中第二层conv2d的输入应该是outputs_1[0]吧，而不是每次都是input_x1。代码是theano_cnn版本

**Comment by white127** [comment]
为什么是outputs呢？
卷积的输入应该是input，对词向量组成的矩阵进行卷积

**Comment by white127** [comment]
github已给出答复

2016-09-23 17:52 GMT+08:00 snowlord notifications@github.com:

**Comment by snowlord** [comment]
@white127 谢谢！
