### ISSUE TITLE
感觉代码中并没有使用到word2vec训练的vectors.nobin中的权重来初始化网络参数？

### ISSUE THREAD

**Issue by jiangqb** [white127/insuranceQA-cnn-lstm#22]
网络权值的初始化仍然是使用tf.random_uniform()使初始权重服从均匀分布？不知道有没有理解错误，望解答。

**Comment by jiangqb** [comment]
load_vectors()函数代码显示对于vectors.nobin中的每个单词分别用100维的向量表示，然而对于load_vectors()得到的self.vectors并没有用起来？

**Comment by white127** [comment]
用的是随机初始化的向量，哎这份数据上，这个对模型效果影响不是很大，也就是随机初始化的向量在训练过程中也能比较好的收敛

2018-07-10 15:41 GMT+08:00 jiangqb <notifications@github.com>:

**Comment by jiangqb** [comment]
嗯嗯好的，但是最后训练的模型在test2上测试top1只有30%多，不知道是不是自己测试代码写的有误。。。

**Comment by jiangqb** [comment]
嗯嗯好的，谢谢解答。就是最后训练好的模型在test2上top1只有30%多，不知道是不是自己测试代码写得有误。。
